import React, { Component } from 'react';
import { Button } from 'react-bootstrap';
import { Grid, Row, Col } from 'react-bootstrap';
import { Route } from 'react-router-dom';
import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    en:{
      returnHome: 'Back to Home',
      pageTitle: 'Terms of Services'
    },
    zh: {
      returnHome: '返回主頁',
      pageTitle: '服務條款'
    }
});

const ButtonToRegionList = ({ title, history, languageChanged }) => (
    <Button bsStyle="" className="button" onClick={() => history.push(`/${languageChanged}/`)}>{strings.returnHome}</Button>
  );

export default class TermsOfServices extends Component {

    componentDidMount() {
        window.scrollTo(0, 0);
    }

    componentWillReceiveProps (nextProps) {
        if (nextProps.languageChanged==='zh') {
            strings.setLanguage('zh');
        } else if (nextProps.languageChanged==='en') {
            strings.setLanguage('en');
        }
    }

    componentWillMount() {
        strings.setLanguage(this.props.languageChanged);
    }

    render() {

        return (
            <div className="no-padding text-page-container">
                <div className="text-page-about">
                    <Grid>
                        <Row>
                            <h2 className="text-page-title"><span>{strings.pageTitle}</span></h2>
                            <Col sm={1}></Col>
                            <Col sm={10}>
                            <div className="text-page-text">
                                <p className="font-italic bold">Last Updated: September 26, 2017</p>
                                <p className="font-italic bold">如果您需要中文的服務條款，請聯絡客戶服務熱線或客戶服務電郵 (please contact support via email or hotline if you would like to request our terms of services in another language)</p>
                       
                                <p>WELCOME TO MAYDAISY.COM.  THE SITE IS OWNED AND OPERATED BY, MAYDAISY COMPANY. (HEREAFTER “MAYDAISY”).  PLEASE READ THESE TERMS OF USE (THIS "AGREEMENT") CAREFULLY BEFORE USING MAYDAISY.COM, ITS MOBILE APPLICATIONS AND SOCIAL MEDIA PAGES (INCLUDING FACEBOOK, INSTAGRAM AND TWITTER PAGES) AND ANY SERVICES OFFERED THROUGH MAYDAISY.COM, ITS MOBILE APPLICATIONS AND AFFILIATED SOCIAL MEDIA OR THIRD PARTY WEB PAGES (COLLECTIVELY REFERRED TO HEREAFTER AS THE “SITE ”).  THIS AGREEMENT SETS FORTH THE LEGALLY BINDING TERMS AND CONDITIONS FOR YOUR USE OF MAYDAISY.</p>
                                <p>By using Site in any manner, including but not limited to visiting or navigating any part of maydaisy.com, all users of the Site (including, without limitation, Florists and Customers as defined below) agree to be bound by this Agreement, including those additional terms and conditions and policies referenced and/or available by hyperlink herein.  This Agreement applies to all users of the Site, including without limitation users who are florists, vendors, customers, merchants, contributors of content, information and other materials or services on the Site or in connection with MayDaisy.  Different sections of the Agreement may affect users different depending upon their use of the Site, so please make sure to review this Agreement carefully.</p>
                                <p>You acknowledge and agree that the Site is solely a venue and has no responsibility or liability for any content, for example, data, text, information, usernames, graphics, images, photographs, profiles, audio, video, items, and links posted by you, other users, or outside parties on the Site.  Your use the Site is solely at your own risk.</p>

                                <h3>1. MayDaisy is a Venue</h3>
                                <p>MayDaisy provides a venue where flower sellers (“Florists”) can create listings to sell certain floral arrangements and limited related goods within a fixed-price format at the Site (subject to compliance with the Florist’s Terms and Conditions set forth below)  and customers who visit  or utilize the Site can learn about Florists’ listings and make purchases from Florists (“Customers”).  MayDaisy is not directly involved in or otherwise a party to any transactions that may take place between Florists and Customers.  MayDaisy has  no control over the quality, safety, morality or legality of any aspect of the Florist’s listings or any claims made by Florists about the products or services they offer, the truth or accuracy of the listings created by Florists, the ability of Florists to sell the items or the ability of Customer to pay for the items. MayDaisy does not conduct background checks regarding any users of the Site and our verification process for Florists is limited.  MayDaisy is not a broker, agent or insurer for any users of the Site, whether they be Florists or Customers.   MayDaisy makes no representations, warranties or guarantees regarding any content or information provided by the florists, including, without limitation, the identity, age, and nationality of any seller, buyer or user.  We encourage you to communicate directly with potential transaction partners through the tools available through MayDaisy.  All purchases made by Customers from Florists are made at each Customer’s own risk.</p>
                                <p>We provide Visitors and Subscribers with access to our Website and Platform as described in this Agreement.</p>
 
                                <h3>2. Membership Eligibility</h3>
                                <p>Registration for membership at the Site is subject to the following additional terms and conditions:Age: MayDaisy is available only to, and may only be used by, individuals who are 18 years of age and older, and who can form legally binding contracts under applicable law.  By registering with the Site, you represent and warrant that you are at least 18 years old and that all registration information you submit is accurate and truthful.  We may, in our sole discretion, refuse to offer access to or use of MayDaisy to any person or entity and change the eligibility criteria at any time.  This foregoing is void where prohibited by law and the right to access MayDaisy is revoked in such jurisdictions.</p>
                                <p>Authority: If you are registering as a business entity, you personally guarantee that you have the authority to bind the entity you are acting on behalf of to this Agreement.</p>
                                <p>Password: Keep your password secure. You are fully responsible for all activity, liability and damage resulting from your failure to maintain password confidentiality. You agree to immediately notify MayDaisy of any unauthorized use of your password or any breach of security. You also agree that we cannot and will not be liable for any loss or damage arising from your failure to keep your password secure. You agree not to provide your username and password information in combination to any other party other than MayDaisy without our express written permission.</p>
                                <p>Account Information: You must keep your account information, including a valid email address, up-to-date and accurate and up to date at all times.  To sell items on MayDaisy you must provide and maintain valid payment information.</p>
                                <p>Account Transfer:  The access rights granted to you under this Agreement are non-transferable without our express written permission. You may not assign or otherwise transfer this Agreement to anyone, including any parent, subsidiaries, affiliated entities or third parties, without our prior written consent, which may be withheld in our reasonable discretion.  Any attempted assignment or other transfer without such consent shall be void, and any such attempt shall be deemed to be a breach of this Agreement. All of our rights and obligations under this Agreement are freely assignable by MayDaisy. As used herein, the terms “assignment” and “transfer” shall include (a) any sale or transfer of all or substantially all of your assets, (b) a merger, consolidation or reorganization, and (c) a change in ownership.</p>
                                <p>Right to Refuse Service: We reserve the right, in our sole discretion, to cancel unconfirmed or inactive accounts. Further, we reserve the right to refuse service to anyone, for any reason, at any time.</p>
                                <p>Compliance: You agree to comply with all local laws regarding online conduct and acceptable content.  In addition, you must abide by our policies as stated in this Agreement and the policy documents listed below (if applicable to your activities on or use of the Site) as well as all other operating rules, policies and procedures that may be published from time to time on the Site by MayDaisy, each of which is incorporated herein by reference and each of which may be updated by MayDaisy from time to time without notice to you:</p>
                                <ul>
                                    <li><a href="https://maydaisy.com/privacy-policy">Privacy Policy</a></li>
                                </ul>
                                <p>Eligibility for Registration as a Florist at the Site is subject to the following additional terms and conditions: </p>
                                <ul>
                                    <li>Florist Legal Obligations - If you would like to register as a Florist, you must be an authorized seller of floral arrangements and related goods through MayDaisy in the jurisdiction where you reside and in compliance with any local laws or regulations.  Where applicable, each Florist is solely responsible for obtaining all permits, licenses or other permissions required to offer goods through the Site.  MayDaisy assumes no responsibility for any Florist’s failure to obtain such permits, licenses or permissions or otherwise comply with applicable laws and regulations.</li>
                                    <li>Single Account Restriction - Only one membership account per Florist is permitted.</li>
                                    <li>No more filling to value - All orders should be prepared with the look and temperament your customer is expecting. Your reputation depends on it.</li>
                                    <li>Images in Listings – Florist may not utilize wire-service or stock photos in its listings.  The images that Florists post in the listings must be images of your own creation featuring your own designs or those created by MayDaisy as part of its service to the Florist.  By posting them with the listing, Florists are each representing and warranting the posted images do not infringe on anyone else’s copyright or intellectual property rights.</li>
                                    <li>Delivery area – The delivery area in the listing must accurately represent the area the Florist is capable of hand delivering arrangements to.</li>
                                    <li>No “order gathering” or resales – MayDaisy has absolutely no tolerance for order gathering.  Florists may only create listings and accept orders that it is capable of fulfilling on its own.  No wiring or reselling orders is permitted and will result in immediate termination of membership.</li>
                                    <li>The Customers are Your Customers – MayDaisy is not the broker, agent or joint venturer of any Florist.  There is no hiding behind a middle man.  Florists must treat all of orders obtained from Customers through the Site as if they are from someone that has just walked into your flower shop.  Happy customers make repeat customers.</li>
                                    <li>Your Customer is Your Responsibility – If there is an issue with an order, Florists are solely responsible for addressing those issues with the Customer directly.  Via the ordering process on the Site, Florists will be provided with Customer contact information and must work directly with them to resolve any issues.  If no resolution can be reached, Florists and Customers may address their concerns to MayDaisy and MayDaisy may elect to act as an intermediary, but is under no independent obligation to do so.</li>
                                    <li>Privacy Policy Compliance:  Florists are solely responsible for complying with all applicable laws, including those governing the collection, use and disclosure of user information.  Although MayDaisy may provide platforms (e.g. Listings, Storefonts, Custom Sites)  for Florists to serve customers, Florists must provide users with all requisite disclosures relative to the collection of personally identifiable information of users by Florists, including, but not limited to, the prominent display of a privacy policy.  To the extent Florists utilize MayDaisy’s platforms to communicate with their users, Florists represent and warrant that they have obtained such user’s authorization to send them e-mails for the Florist’s marketing or promotional purposes. For any email obtained from a user outside of MayDaisy’s platform and imported into his or her MayDaisy profile for our email marketing services, Florists must first have obtained the user’s authorization to send them e-mails for the Florist’s marketing or promotional purposes.</li>
                                </ul>
                                <p>Florists that do not abide to the above terms and conditions and those listed below are subject to immediate removal without written or advance notification from MayDaisy.  Users are encouraged to report any violations of the foregoing terms and conditions by a Florist by contacting MayDaisy at contact@maydaisy.com.</p>

                                <h3>3. Marketplace/Storefront/Fees/Taxes and Payments</h3>
                                <p>Fees:  Joining and setting up a Storefront on MayDaisy is free for registered Florists. Florists are charged up to twenty percent (20%) commission fee based on the total dollar amount of the order received via MayDaisy (either directly or through affiliated third party web and mobile sites), excluding sales tax, HST, PST, and/or GST if applicable. MayDaisy has the sole discretion to adjust this commission rate between the range zero to twenty percent (0%-20%) without consulting or notifying florists. The spirit of having this variable commission fee is to provide MayDaisy a flexible marketing budget during high floral seasons while providing as much value back to florists as possible.</p>
                                <p>Relative to all of the foregoing options, MayDaisy reserves the right, at our sole discretion, change some or all of MayDaisy's services at any time.  In the event we introduce a new service, the fees for that service are effective at the launch of such service.  Unless otherwise stated, all fees are quoted in Hong Kong Dollars (HKD).  We keep accepted payment information on file.  We shall not be responsible in any way for any fraudulent payment or credit information provided by any third parties.</p>
                                <p>Taxes: Florists are responsible for collecting and remitting all applicable sales and government taxes in relation to transactions conducted through the Storefront by including it into their product pricing.</p>
                                <p>Payments:  Settled transactions will be debited to your account balance via direct deposit or a check mailed to your address on file with MayDaisy, within a reasonable time after the order has been processed and the buyer’s credit card has been authorized.  In no event shall the payment time exceed thirty-one (31) days from the end of the month in which the order was delivered and the buyer’s credit card has been authorized. MayDaisy reserves the right to withhold, reverse or otherwise refuse payments to Florists for any unfulfilled or returned customer transactions, including, without limitation, refunds due to non-delivery by Florist, customer rejections for quality issues, non-payment due to customer fraud, chargeback or contested charges.</p>

                                <h3>4. Listings - Responsibilities of Florists</h3>
                                <p>Listing Description: By listing an item on MayDaisy Florists warrant that you and all aspects of the item comply with this Agreement. Florists also warrant that they may legally sell the item. Florists must accurately describe your item and all terms of sale in its Storefront. Florist’s listings may only include text descriptions, graphics, pictures and other content applicable to the sale of that item. All items must be listed in an appropriate category with appropriate tags. Each listing must accurately and completely describe the item/items for sale in that listing.  Each unique item must have its own listing.  The price stated in each item listing description must be an accurate representation of the sale.  Florist may not misrepresent the item's location, or use another user's account without permission.</p>
                                <p>Binding Sale:  All sales are binding. The Florist is obligated to deliver the order or otherwise complete the transaction with the Customer in a prompt manner, unless there is an exceptional circumstance, such as: (a) the Customer fails to meet the terms of the Florist's listing (such as payment method), or (b) the Florist cannot authenticate the Customer’s identity. The Customer is obligated to deliver appropriate payment for items purchased, unless there is an exceptional circumstance. In the event that an order is received that you are unable to deliver, you are responsible for promptly notifying MayDaisy so that the order can be forwarded to another florist to fulfill or so that the order can be canceled and refunded to the customer in a timely manner.</p>
                                <p>Responsibilities: Notwithstanding anything to the contrary herein, Florists are solely responsible for all orders placed through its Storefront, whether such orders are lost, unprocessed, mishandled or otherwise.  Florists remain solely responsible even if such failure to fulfill the order is a result of not checking notifications sent to the Florist via MayDaisy. Florists are also solely responsible for informing the Customer of any lost, unprocessed or mishandled orders, and for all other Customer relationship matters relating to orders processed through the Florist’s Storefront.  We are not responsible in any way whatsoever for the foregoing matters.</p>

                                <h3>5. Prohibited, Questionable and Infringing Items and Activities by All Users</h3>                                
                                <p>Each user is solely responsible for his/her/its conduct and activities on and regarding to the Site and any and all data, text, information, usernames, graphics, images, photographs, profiles, audio, video, items, and links (together, "Content") that the user submits, posts, and displays on the Site. Furthermore, Florists may not list any item on the Site (or consummate any transaction that was initiated using the Site) that, by paying to MayDaisy the final value fee, could cause MayDaisy to violate any applicable law, statute, ordinance or regulation, or that violates this Agreement.</p>
                                <p>Restricted Activities: Your Content and your use of the Site shall not:</p>
                                <ul>
                                    <li>Be false, inaccurate or misleading.</li>
                                    <li>Be fraudulent or involve the sale of illegal, counterfeit or stolen items.</li>
                                    <li>Infringe upon any third-party's copyright, patent, trademark, trade secret or other proprietary or intellectual property rights or rights of publicity or privacy.</li>
                                    <li>Violate this Agreement, any site policy, or any applicable law, statute, ordinance or regulation (including, but not limited to, those governing export control, consumer protection, unfair competition, anti-discrimination or false advertising).</li>
                                    <li>Contain items that have been identified by the applicable jurisdiction as hazardous to consumers and therefore subject to a recall.</li>
                                    <li>Be defamatory, discriminatory, trade libelous, unlawfully threatening, unlawfully harassing, impersonate or intimidate any person (including our staff or other users), or falsely state or otherwise misrepresent your affiliation with any person through, for example, the use of similar email address, nicknames, or creation of false account(s) or any other method or device.</li>
                                    <li>Be obscene or contain child pornography.</li>
                                    <li>Contain or transmit any code of a destructive nature that may damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information.</li>
                                    <li>Host images not part of a listing.</li>
                                    <li>Modify, adapt or hack the Site or modify another website so as to falsely imply that it is associated with MayDaisy.</li>
                                    <li>Appear to create liability for MayDaisy or cause MayDaisy to lose (in whole or in part) the services of MayDaisy's ISPs or other suppliers.</li>
                                    <li> Link directly or indirectly, reference or contain descriptions of goods or services that are prohibited under this Agreement, other agreements hyperlinked herein, or other policy documents as posted on the Site.</li>
                                    <li>Use the Site to collect orders for any other business to fulfill.</li>
                                    <li>Reproduce, duplicate, copy, sell, trade or resell any of the services within the Site for any purpose.</li>
                                    <li>Engage in activity that interferes with or disrupt the Site (or the servers and networks which are connected to the Site).</li>
                                    <li>Contain alcohol</li>
                                </ul>
                                <p>Notwithstanding anything to the contrary herein, we reserve the right (but shall have no obligation) to pre-screen, review, flag, filter, modify, refuse or remove any or all Content from the Site.</p>

                                <h3>6. Content, Material & Licenses</h3>  
                                <p>We own all legal right, title and interest in and to the Site, including any intellectual property rights which subsist in the Site, whether those rights happen to be registered or not, and wherever those rights may exist.  Unless you have agreed otherwise in writing with MayDaisy, nothing in this Agreement gives you a right to use any of MayDaisy’s trade names, trademarks, service marks, logos, domain names and other distinctive brand features.</p>
                                <p>Copyright Ownership of MayDaisy Generated Content:  As part of its services to Florists, MayDaisy (either directly or through one of its authorized contractors) may create or otherwise generate images of certain products offered by Florists (hereafter, “MayDaisy Generated Content”) which may then be utilized to advertise or other sell the respective Florist’s products through Storefronts.  By availing themselves of this service, Florists acknowledge and agree that MayDaisy owns any and all rights to use, publish, and copyright MayDaisy Generated Content in any and all media, now or hereafter known.  Florists further release to MayDaisy all rights to exhibit this MayDaisy Generated Content (even if it includes or otherwise encompasses any work that Florist may claim copyright upon) in any and all media, now or hereafter known, publicly or privately.  Florists further acknowledge and agree that they have no right, title, or interest in or to any of the MayDaisy Generated Content and hereby release and hold harmless MayDaisy and its successors and assigns from any damages or liability relating to or arising from any use of or modification or alteration to any of the MayDaisy Generated Content; and hereby waive any claims they may have based on any use of the MayDaisy Generated Content or works derived therefrom.  Florists further acknowledge and understand that, in the event Florists’ account with MayDaisy is terminated (for any reason and whether by MayDaisy or the subject Florist), Florists shall have no right to use any MayDaisy Generated Content, absent the express, written content of MayDaisy, and must promptly remove any MayDaisy Generated Content from any materials their publish or distribution in any forum (online or otherwise.)</p>
                                <p>MayDaisy License to User Generated Content: MayDaisy does not claim ownership rights in user content which is content generated solely by its users and expressly defined as not including MayDaisy Generated Content (hereafter, “User Content”). However, by submitting User Content to the Site, users grant MayDaisy (and its affiliated third party websites and their operators) a license to fully enable MayDaisy (and affiliates) to use any information or User Content you supply MayDaisy with, so that MayDaisy is not violating any rights you might have in that Content. By submitting User Content to the Site, users further grant MayDaisy and its affiliates a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sublicensable (through multiple tiers) right to exercise the copyright, publicity, and database rights (but no other rights) the user has in the User Content, in any media now known or not currently known, with respect to the User Content. Users agree to allow MayDaisy and its affiliates to store or re-format their User Content on or through the Site and display your User Content on or through the Site in any way as we choose (including for advertising, marketing or other promotional purposes relative to MayDaisy).  MayDaisy’s use personal information submitted by users shall be governed by and in accordance with MayDaisy's Privacy Policy.</p>
                                <p>Florists explicitly grant to MayDaisy (and its affiliated third party websites and their operators) a perpetual, irrevocable, worldwide, royalty-free, and non-exclusive license to reproduce, adapt, modify, translate, publish, publicly perform, publicly display and distribute any User Content, Florists submit, post or display on or through the Site (including affiliated third party websites), or post or display on a Florist’s Storefront. Florists are solely responsible to ensure the User Content posted is of their own images, copyright and intellectual property or that the Florists have the express written consent to use such User Content.  Florists hereby further grant to MayDaisy the right to promote the services provided to Florists in MayDaisy press kits, press releases, and any other promotional materials related to MayDaisy. Florists acknowledge MayDaisy as the creator and provider of the Site.  Unless provided otherwise in a separate written agreement between the Florist and MayDaisy, Florists acknowledge and agree that each of them are solely responsible for protecting and enforcing any rights the Florist may have to any User Content that submitted, posted, transmitted or displayed on, or through, the Site and that MayDaisy has no obligation to protect or enforce those rights on the Florist’s behalf.</p>
                                <p>Users confirm and warrant to MayDaisy that they have all the rights, power and authority necessary to grant the above licenses to User Content.</p>
                                <p>As part of a transaction, Florists may obtain personal information, including email address and shipping information, from another user.  Without obtaining prior permission from the other user, this personal information shall only be used for that transaction or for MayDaisy related communications. MayDaisy does not grant any users a license to use any personal information of any other user for unsolicited commercial messages.  Without limiting the foregoing and without express consent from the user, users are not licensed to add any MayDaisy user to any email or physical mail list. For more information, see MayDaisy's Privacy Policy.</p>
                                <p>Re-Posting Content: By posting User Content on MayDaisy, it is possible for an outside website or a third party may re-post that User Content. Users agree to indemnify and hold MayDaisy harmless for any dispute, claims or causes that may arise from any such action.</p>
                                <p>Idea Submissions: We consider any unsolicited suggestions, ideas, proposals or other material submitted to MayDaisy by users (other than the User Content and the tangible items sold on MayDaisy by users) (collectively, the "Material") to be non-confidential and non-proprietary, and MayDaisy shall not be liable for the disclosure or use of such Material.  If, at MayDaisy’s request, any member sends Material to improve the Site (for example through the forums or to customer support), MayDaisy will also consider that Material to be non-confidential and non-proprietary and MayDaisy will not be liable for use or disclosure of the Material.  Any communication by users to MayDaisy is subject to this Agreement.  Users hereby grant and agree to grant to MayDaisy, under all of such user’s rights in the Material, a worldwide, non-exclusive, perpetual, irrevocable, royalty-free, fully-paid, sublicensable and transferable right and license to incorporate, use, publish and exploit such Material for any purpose whatsoever, commercial or otherwise, including but not limited to incorporating it in the API, documentation, or any product or service, without compensation or accounting to the user and without further recourse by the user.</p>

                                <h3>7. Information Control</h3>  
                                <p>MayDaisy has limited control of the User Content provided by users and that is made available on the Site.  You may find some User Content to be offensive, harmful, inaccurate, or deceptive. There are also risks of dealing with underage persons or people acting under false pretense.</p>
                                <p>Additionally, there may also be risks of dealing with international trade and foreign nationals. By using the Site, users agree to accept such risks and that MayDaisy and its officers, directors, agents, subsidiaries, joint ventures, employees, suppliers, licensors and representatives (collectively, MayDaisy’s “Affiliates”), are not responsible for any and all acts or omissions of users on the Site. Please use caution, common sense, and practice safe buying and selling when using the Site.</p>
                                <p>Other Resources: MayDaisy is not responsible for the availability of outside websites or resources linked to or referenced on the Site.  We do not endorse and are not responsible or liable for any content, advertising, products, or other materials on or available from such websites or resources. Users agree that we shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such websites or resources.</p>

                                <h3>8. Meetings & Groups</h3> 
                                <p>Meetings: Users may arrange and attend online virtual meetings or in-person meetings ("Meetings") with one or more individuals.  Users are solely responsible for all interactions with other users at Meetings. Users must comply with MayDaisy's policies and acknowledge and agree to comply with the laws of the city, county and country in which the Meeting occurs. Additional eligibility requirements for a particular group or Meeting may be set by the group's contact person. MayDaisy is not involved with user generated groups, the groups' requirements, or the Meetings.</p>
                                <p>MayDaisy does not supervise or control the Meetings, user-initiated online or offline gatherings, or the interactions among and between users and other persons or companies. Users are solely responsible for interactions with other users. Users understand that we do not in any way screen or conduct background checks its users. All users agree to exercise caution and good judgment in all interactions with others, particularly if meeting offline or in person.</p>
                                <p>Groups or User Fees: Some user-generated groups on MayDaisy may require or request that users pay fees in order to be a member of the group, participate in a promotion, or participate in Meetings. ANY SUCH FEES ARE GOVERNED SOLELY BY THE SUBJECT USERS AND MayDaisy IS NOT INVOLVED IN THE REQUEST FOR, OR COLLECTION OR PAYMENT OF SUCH FEES AND RELATED TRANSACTIONS, THE PAYMENTS OR THEIR PROCESSING.  THE PAYMENT DOES NOT GO TO MayDaisy; THIS MONEY IS SEPARATE FROM ANY FEES OR CHARGES ASSESSED BY MayDaisy, AND WE HAVE NO CONTROL OVER THE FEES, THE USER-GENERATED GROUPS, PROMOTIONS, THE MEETINGS, OR THE LEADER OF THE GROUP IN CONNECTION WITH ITS USE.  BY PARTICIPATING IN MEETINGS, USERS ACKNOWLEDGE AND AGREE THAT MayDaisy IS NOT INVOLVED OR OTHERWISE A PARTY TO ANY TRANSACTION OR INTERACTION BETWEEN OR AMONG USER-GENERATED GROUPS, MayDaisy USERS AND/OR THIRD PARTIES (TOGETHER A "THIRD PARTY TRANSACTION"), AND THAT YOU BEAR ALL RISK IN CONNECTION WITH YOUR THIRD PARTY TRANSACTIONS.  USERS SHOULD USE COMMON SENSE AND BE CAREFUL IN DECIDING WHETHER TO CONTRIBUTE MONEY TO SUCH RELATED TRANSACTIONS.</p>

                                <h3>9. Resolution of Disputes and Release</h3> 
                                <p>In the event a dispute arises between a user and MayDaisy, the user should contact MayDaisy at contact@MayDaisy.com to assess the possibility of informal resolution.</p>
                                <p>Barring such informal resolution, any dispute arising from or relating to the subject matter of this Agreement or a user’s use of the Site or relationship with MayDaisy shall be finally settled by binding arbitration in Hong Kong SAR, using the English language in accordance with the Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, LLC. ("JAMS") then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of JAMS arbitrators in accordance with the Comprehensive Arbitration Rules and Procedures of JAMS.  The prevailing party in any arbitration or other proceeding arising under this Agreement shall be entitled to receive reimbursement of its reasonable expenses (including reasonable attorneys' fees, expert witness fees and all other expenses) incurred in connection therewith.  Judgment upon the award so rendered may be entered in a court having jurisdiction or application may be made to such court for judicial acceptance of any award and an order of enforcement, as the case may be.  Notwithstanding the foregoing, each party shall have the right to institute an action in a court of proper jurisdiction for injunctive or other equitable relief pending a final decision by the arbitrator.  For all purposes of this Agreement, the parties consent to exclusive jurisdiction and venue in the courts located in Hong Kong SAR. Use of the Site is not authorized in any jurisdiction that does not give effect to all provisions of this Agreement, unless expressly noted otherwise herein, including without limitation, this section.</p>
                                <p>Should a dispute arise between you and any other user or users of the Site, or an outside party, you release MayDaisy and its Affiliates from any and all claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes. MayDaisy encourages users to report user-to-user disputes to your local law enforcement, postmaster general, or a certified mediation or arbitration entity, as applicable and appropriate.</p>
                                <p>MayDaisy, for the benefit of users, may elect to assist users resolve disputes, however, MayDaisy do so in its sole and exclusive discretion, and MayDaisy undertakes no formal obligation to resolve disputes between users or between users and outside parties. To the extent that MayDaisy attempts to resolve such disputes, MayDaisy does so in good faith and based solely on its policies. MayDaisy  will not make judgments regarding legal issues or claims.</p>

                                <h3>10. MayDaisy's Intellectual Property</h3> 
                                <p>MayDaisy, and other MayDaisy graphics, logos, designs, page headers, button icons, scripts, and service names are registered trademarks, trademarks or trade dress of MayDaisy, Inc. in Hong Kong and/or other countries.  MayDaisy's trademarks and trade dress may not be used, including as part of trademarks and/or as part of domain names or email addresses, in connection with any product or service in any manner that is likely to cause confusion.</p>

                                <h3>11. Access and Interference</h3>
                                <p>The Site may contain robot exclusion headers which contain internal rules for software usage.  Much of the information on the Site is updated on a real-time basis and is proprietary or is licensed to MayDaisy by the Site’s users or third-parties. You agree that you will not use any robot, spider, scraper or other automated means to access the Site for any purpose whatsoever, except to the extent expressly permitted by and in compliance with this Agreement or otherwise without our prior express written permission. Additionally, you agree that you will not:</p>
                                <ul>
                                    <li>Take any action that imposes, or may impose, in our sole discretion, an unreasonable or disproportionately large load on MayDaisy;s infrastructure.</li>
                                    <li>Copy, reproduce, modify, create derivative works from, distribute or publicly display any user Content (except for your Content) or other allowed uses as set out in this Agreement from the Site except to the extent expressly permitted by and in compliance with this Agreement or otherwise without the prior express written permission of MayDaisy and the appropriate third party, as applicable.</li>
                                    <li>Interfere or attempt to interfere with the proper working of the Site or any activities conducted thereon.</li>
                                    <li>Bypass the Site’s robot exclusion headers or other measures we may use to prevent or restrict access to the Site.</li>
                                </ul>
                                
                                <h3>12. Breach</h3> 
                                <p>Without limiting any other remedies, MayDaisy may, without notice, and without refunding any fees, delay or immediately remove Content, warn MayDaisy's community of a user's actions, issue a warning to a user, temporarily suspend a user, temporarily or indefinitely suspend a user's account privileges, terminate a user's account, prohibit access to MayDaisy, and take technical and legal steps to keep a user off MayDaisy and refuse to provide services to a user if, not intended to be an exclusive list, any of the following apply:</p>
                                <ul>
                                    <li>We suspect (by information, investigation, conviction, settlement, insurance or escrow investigation, or otherwise) a user has breached this Agreement, the Privacy Policy or other policy documents and community guidelines incorporated herein.</li>
                                    <li>We are unable to verify or authenticate any of the user’s personal information or Content.</li>
                                    <li>We believe that a user is acting inconsistently with the letter or spirit of MayDaisy's policies, has engaged in improper or fraudulent activity in connection with the Site or the actions may cause legal liability or financial loss to MayDaisy's users or to MayDaisy itself.</li>
                                </ul>

                                <h3>13. Privacy</h3> 
                                <p>Any personal information you submit to the Site or MayDaisy is governed by MayDaisy's Privacy Policy .  This Privacy Policy encompasses any and all information you may provide to the Site or MayDaisy either for purposes of becoming a Member of the Site, submitting feedback about the Site or any content or other users of the Site, or to receive further information, updates and promotions about or related to the Site or MayDaisy.  Except as disclosed in MayDaisy's Privacy Policy, we will not sell or disclose your personal information (as defined in the Privacy Policy) to third parties without your explicit consent.</p>

                                <h3>14. No Warranty</h3> 
                                <p>MayDaisy AND ITS AFFILIATES PROVIDE THE SITE "AS IS" AND WITHOUT ANY WARRANTY OR CONDITION, EXPRESS, IMPLIED OR STATUTORY. YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE SITE IS AT YOUR SOLE RISK AND THAT MayDaisy AND ITS AFFILIATES DO NOT REPRESENT OR WARRANT TO YOU THAT:  (i) YOUR USE OF THE SITE WILL MEET YOUR REQUIREMENTS; (ii) YOUR USE OF THE SITE WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR; (iii) ANY INFORMATION OBTAINED BY YOU AS A RESULT OF YOUR USE OF THE SITE WILL BE ACCURATE OR RELIABLE; AND (iv) THAT DEFECTS IN THE OPERATION OR FUNCTIONALITY OF ANY SOFTWARE PROVIDED TO YOU AS A PART OF THE SITE WILL BE CORRECTED.  MayDaisy AND ITS AFFILIATES SPECIFICALLY DISCLAIM ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, PERFORMANCE, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN ADDITION, NO ADVICE OR INFORMATION (ORAL OR WRITTEN) OBTAINED BY YOU FROM MayDaisy OR ITS AFFILIATES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS AGREEMENT. SOME STATES DO NOT ALLOW THE DISCLAIMER OF IMPLIED WARRANTIES, SO THE FOREGOING DISCLAIMER MAY NOT APPLY TO YOU.  YOU MAY ALSO HAVE OTHER LEGAL RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.</p>
                                
                                <h3>15. Liability Limitation</h3> 
                                <p>MayDaisy AND ITS AFFILIATES SHALL NOT BE LIABLE TO YOU FOR: (i) ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES WHICH MAY BE INCURRED BY YOU, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, INCLUDING, BUT NOT LIMITED TO, ANY LOSS OF PROFIT (WHETHER INCURRED DIRECTLY OR INDIRECTLY), ANY LOSS OF GOODWILL OR BUSINESS REPUTATION, ANY LOSS OF DATA SUFFERED, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR OTHER INTANGIBLE LOSS; AND (ii) ANY LOSS OR DAMAGE WHICH MAY BE INCURRED BY YOU, INCLUDING, BUT NOT LIMITED TO, LOSS OR DAMAGE AS A RESULT OF (a) ANY CHANGES WHICH WE MAY MAKE TO THE SITE, OR FOR ANY PERMANENT OR TEMPORARY CESSATION IN PROVIDING THE SITE (OR ANY SERVICES OFFERED THROUGH OR FEATURES WITHIN THE SITE), (b) THE DELETION OF, CORRUPTION OF, OR FAILURE TO STORE, ANY CONTENT AND OTHER COMMUNICATIONS DATA MAINTAINED OR TRANSMITTED BY OR THROUGH YOUR USE OF THE SITE, (c) YOUR FAILURE TO PROVIDE MayDaisy WITH ACCURATE ACCOUNT INFORMATION, (d) YOUR FAILURE TO KEEP YOUR PASSWORD OR ACCOUNT DETAILS SECURE AND CONFIDENTIAL, (e) YOUR USE OR MISUSE OF THE SITE, (f) ERRORS, DEFECTS, DELAYS IN OPERATION OR TRANSMISSION, AND/OR (g) HYPERLINKS TO WEB SITES OR CONTENT OR RESOURCES PROVIDED BY COMPANIES OR PERSONS OTHER THAN MayDaisy.   THESE FOREGOING LIMITATIONS ON OUR LIABILITY SHALL APPLY WHETHER OR NOT WE HAVE BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING.</p>
                                <p>In no event shall MayDaisy or our suppliers be liable for lost profits or any special, incidental or consequential damages arising out of or in connection with our site, our services or these Terms of Service (however arising including negligence). You agree to indemnify and hold us and (as applicable) our parent, subsidiaries, affiliates, MayDaisy partners, officers, directors, agents, employees, and suppliers harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of your breach of these Terms of Service or the documents it incorporates by reference, or your violation of any law or the rights of a third party.</p>
                                <p>Your use of the Service is at your sole risk. The Service is provided on an “as is” and “as available” basis without any warranty or condition, express, implied or statutory.</p>
                                <p>MayDaisy does not warrant that the Service will be uninterrupted, timely, secure, or error-free.</p>
                                <p>MayDaisy does not warrant that the results that may be obtained from the use of the Service will be accurate or reliable.</p>
                                <p>MayDaisy does not warrant that the quality of any products, services, information, or other material purchased or obtained by you through the Service will meet your expectations, or that any errors in the Service will be corrected.</p>

                                <h3>16. Indemnity</h3>
                                <p>YOU AGREE TO INDEMNIFY AND HOLD MayDaisy AND  ITS AFFILIATES, HARMLESS FROM AND AGAINST ALL DAMAGES, COSTS (INCLUDING, WITHOUT LIMITATION, SETTLEMENT COSTS), LOSSES, EXPENSES, (INCLUDING WITHOUT LIMITATION, REASONABLE ATTORNEYS' FEES) AND LIABILITIES RELATING TO ANY CLAIM OR DEMAND ASSERTED BY ANY PARTY AGAINST MayDaisy AND/OR ITS AFFILIATES ARISING FROM OR RELATED TO YOUR ACTIVITES OR CONDUCT ON OR THROUGH THE SITE.</p>

                                <h3>17. Access and Data Integrity</h3>
                                <p>MayDaisy does not guarantee continuous, uninterrupted access to the Site.  Although MayDaisy attempts to maintain the integrity and accuracy of the information on the Site, we make no guarantees as to its correctness, completeness, or accuracy.  The Site may contain typographical errors, inaccuracies, or other errors or omissions. Also, unauthorized additions, deletions, or alterations could be made to the Site by other users or third parties without MayDaisy’s knowledge.  If you believe that information found on the Site is inaccurate or unauthorized, please inform MayDaisy by e-mailing us at contact@MayDaisy.com.</p>

                                <h3>18. Severability</h3>
                                <p>If any provision of this Agreement is held unenforceable, then such provision will be modified to reflect the parties' intention. All remaining provisions of this Agreement shall remain in full force and effect.</p>

                                <h3>19. No Employment or Agency</h3>
                                <p>MayDaisy is not an employment service and does not serve as an employer of any user (Florist, Customer or otherwise).  MayDaisy is not be liable for any tax or withholding, including but not limited to unemployment insurance, employer's liability, social security or payroll withholding tax in connection with any use of the Site.  By using the Site, users understand and agree that, if MayDaisy is found to be liable for any tax or withholding tax in connection with your use of the Site, then you will immediately reimburse and pay to MayDaisy an equivalent amount, including any interest or penalties thereon.</p>
                                <p>No brokerage, agency, partnership, joint venture, employer-employee or franchiser-franchisee relationship is intended or created by this Agreement. Without limiting the foregoing, except as expressly set forth herein, MayDaisy is not acting and does not act as an agent for any Florist, Customer or any other user or visitor of the Site.</p>

                                <h3>20. MayDaisy Service</h3>
                                <p>MayDaisy reserves the right to modify, limit, suspend or terminate any and all services offered on or through the Site (or any feature thereof) for any reason, without notice, at any time. MayDaisy reserves the right to alter this Agreement or other MayDaisy policies at any time, so please review the policies frequently.</p>
                                
                                <h3>21. Amendments</h3>
                                <p>MayDaisy may amend this Agreement at any time, and from time to time, in our sole and absolute discretion, without any notice to you. You should regularly review this Agreement as posted on the Site on this page to check for amendments. You understand and agree that if you use the Site after the date on which these amendments have been applied to the Agreement, MayDaisy will treat your continued use of the Site as acceptance of the updated terms.  You may not amend this Agreement at any time without our prior written consent.</p>
                                
                                <h3>22. No Waiver</h3>
                                <p>You agree that if MayDaisy does not exercise or enforce any legal right or remedy which is contained in this Agreement (or which we have the benefit of under any applicable law), it shall not constitute a waiver of MayDaisy’s rights, and as such, those rights or remedies will still be available to MayDaisy. Nothing in this Agreement shall prevent MayDaisy from complying with the law and these terms do not confer any third party beneficiary rights.</p>
                                
                                <h3>23. Choice of Law</h3>
                                <p>This Agreement shall in all respects be interpreted and construed with and by the laws of Hong Kong SAR, without regard to its conflict of law provisions.</p>
                                
                                <h3>24. Survival</h3>
                                <p>Sections: (Services, Fees/Taxes and Payments), (Content, Material & Licenses), (Information Control), (Meetings & Groups), (Resolution of Dispute and Release), (MayDaisy's Intellectual Property), (Access and Interference), (Breach), (Privacy), (No Warranty), (Liability Limit), (Indemnity), (Severability), (No Agency), (Choice of Law) shall survive any termination or expiration of this Agreement.</p>
                                
                                <h3>25. Notices</h3>
                                <p>Except as explicitly stated otherwise, any notices to MayDaisy shall be sent via postal mail to MayDaisy’s offical contact address and any notices to users (in the case of MayDaisy) shall be sent to the email address you have provided to MayDaisy.  Notice sent by email shall be deemed given twenty-four (24) hours after email is sent, unless the sending party is notified that the email address is invalid.  Alternatively, MayDaisy may elect, at its own discretion, to deliver notice by certified mail, to the address you provided to MayDaisy. In such case, notice shall be deemed given three days after the date of mailing.</p>
                                
                                <h3>26. Contact</h3>
                                <p>If you have any questions about this Agreement, please contact contact@maydaisy.com.</p>

                                <div className="text-page-button-div">
                                    <Route path="/" render={(props) => <ButtonToRegionList {...props} languageChanged={this.props.languageChanged}/>} />
                                </div>
                            </div>
                            </Col>
                            <Col sm={1}></Col>
                        </Row>
                    </Grid>
                </div>
            </div>
        )
    }
}
    